version: "3.7"
services:
  web:
    build: 
      context: src/Logstash.Web
    # image: logstash-web    
    container_name: logstast-web
    ports:
      - "5005:5005"
    volumes:
      - web-volume:/app/logs
    depends_on:
      - elasticsearch
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5005

  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.9.2
    ports:
      - '5601:5601'
    depends_on:
    - elasticsearch
  logstash:
    image: logstash:7.9.2
    links:
    - web    
    volumes:    
    - ./config:/usr/share/logstash/pipeline:ro,Z
    - web-volume:/logs
    depends_on:
    - web 
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 3000M
      restart_policy:
        condition: on-failure
        max_attempts: 3
volumes:
  web-volume: 
